class_name Collision

const STRUCTURE_LAYER = 1
const STRUCTURE_AREA_LAYER = 1 << 2
const STRUCTURE_AREA_MASK = ENTITY_LAYER

const ENTITY_LAYER = 1 << 1
const ENTITY_MASK = STRUCTURE_LAYER | ENTITY_LAYER
const ATTACK_MASK = STRUCTURE_LAYER | ENTITY_LAYER
